# Alternative ESLint action with proper annotations
# This can be used instead of running ESLint directly

name: ESLint Check

on:
  pull_request:
    paths:
      - 'src/**/*.ts'
      - 'eslint.config.js'
      - 'package.json'

jobs:
  eslint:
    name: ESLint Analysis
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      actions: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint with SARIF output
        run: |
          npx eslint src/**/*.ts \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif || true
        continue-on-error: true
        
      - name: Upload ESLint results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
          
      - name: Run ESLint for console output
        run: |
          echo "🔍 Running ESLint for detailed output..."
          npx eslint src/**/*.ts --format=stylish