name: Thai Adblock List Action (Update)

on:
  push:
    paths:
      - "adblock-filters-list/adblock-filters-list.txt"
  workflow_dispatch: # This event allows manual triggering (optional)

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1

      - name: Install dependencies
        run: npm install

      - name: Set timezone to Bangkok
        run: |
          sudo timedatectl set-timezone Asia/Bangkok

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_committer_name: ${{ secrets.NAME }}
          git_committer_email: ${{ secrets.EMAIL }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Export GPG key
        run: |
          echo ${{ secrets.NAME }}
          echo ${{ secrets.EMAIL }}
          echo ${{ secrets.GPG_PRIVATE_KEY }}
          echo ${{ secrets.PASSPHRASE }}

      - name: Run update script
        run: node index.js

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add thai-adblock-list.txt domain.txt
          git commit -S -m "Update $(date +'%d-%m-%Y')"
          git push
