name: Thai Adblock List Update

on:
  push:
    paths:
      - "adblock-filters-list/adblock-filters-list.txt"
  workflow_dispatch: # This event allows manual triggering (optional)

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1

      - name: Install dependencies
        run: npm install

      - name: Set timezone to Bangkok
        run: |
          sudo timedatectl set-timezone Asia/Bangkok

      - name: Run update script
        run: node index.js

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add thai-adblock-list.txt domain.txt
          git commit -S -m "Update $(date +'%d-%m-%Y')"
          git push

      - name: Calculate checksums
        run: |
          sha1sum thai-adblock-list.txt > sha1.txt
          md5sum thai-adblock-list.txt > md5.txt
          sha1sum domain.txt >> sha1.txt
          md5sum domain.txt >> md5.txt
          echo "::set-output name=sha1::$(cat sha1.txt)"
          echo "::set-output name=md5::$(cat md5.txt)"

      - name: Update README-TH.md
        run: |
          sed -i -E "s/SHA-1: .+/SHA-1: ${{ steps.checksums.outputs.sha1 }}/g" README-TH.md
          sed -i -E "s/MD5: .+/MD5: ${{ steps.checksums.outputs.md5 }}/g" README-TH.md
          git add README-TH.md
          git commit -m "Update SHA-1 and MD5 checksums" --author="GitHub Actions <actions@github.com>"
          git push
      
      - name: Update README
        run: |
          sed -i -E "s/SHA-1: .+/SHA-1: ${{ steps.checksums.outputs.sha1 }}/g" README.md
          sed -i -E "s/MD5: .+/MD5: ${{ steps.checksums.outputs.md5 }}/g" README.md
          git add README.md
          git commit -m "Update SHA-1 and MD5 checksums" --author="GitHub Actions <actions@github.com>"
          git push

      - name: Verify checksums
        run: |
          sha1sum thai-adblock-list.txt > sha1_actual.txt
          md5sum thai-adblock-list.txt > md5_actual.txt
          sha1sum domain.txt >> sha1_actual.txt
          md5sum domain.txt >> md5_actual.txt
          echo "::set-output name=sha1_actual::$(cat sha1_actual.txt)"
          echo "::set-output name=md5_actual::$(cat md5_actual.txt)"

      - name: Get expected checksums
        run: |
          grep "SHA-1: " README.md | cut -d' ' -f2 > sha1_expected.txt
          grep "MD5: " README.md | cut -d' ' -f2 > md5_expected.txt
          echo "::set-output name=sha1_expected::$(cat sha1_expected.txt)"
          echo "::set-output name=md5_expected::$(cat md5_expected.txt)"

      - name: Verify checksums
        run: |
          diff -q sha1_actual.txt sha1_expected.txt && echo "SHA-1 OK" || echo "SHA-1 MISMATCH"
          diff -q md5_actual.txt md5_expected.txt && echo "MD5 OK" || echo "MD5 MISMATCH"
